# Generated by Django 5.2 on 2026-01-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gacha", "0002_action_user_gacharesult_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="gacharesult",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
